### ISSUE TITLE
link fails on ubuntu 16.10

### ISSUE THREAD

**Issue by bburdette** [mvdnes/portaudio-rs#17]
pkg-config fails to find portaudio2.0.  but apparently portaudio 19 has the 2.0 interface?  

It also fails on nixos, which has a similar portaudio version.

```
bburdette@BB-5520:~/code/cyclofraust$ cargo build
   Compiling fraust_test v0.1.0 (file:///home/bburdette/code/cyclofraust)
   Compiling portaudio_sys v0.1.1 (https://github.com/mvdnes/portaudio-rs#0b228f54)
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `portaudio_sys v0.1.1 (https://github.com/mvdnes/portaudio-rs#0b228f54)`
process didn't exit successfully: `/home/bburdette/code/cyclofraust/target/debug/build/portaudio_sys-7fcf7834eb92e2bd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "portaudio-2.0"` did not exit successfully: exit code: 1
--- stdout
Package portaudio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `portaudio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'portaudio-2.0' found
', /home/bburdette/.cargo/git/checkouts/portaudio-rs-00e07e26853f2e98/0b228f5/portaudio_sys/build.rs:8
stack backtrace:
   1:     0x5624ba9b619a - std::sys::imp::backtrace::tracing::imp::write::h3188f035833a2635
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5624ba9bb21f - std::panicking::default_hook::{{closure}}::h6385b6959a2dd25b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x5624ba9bae1e - std::panicking::default_hook::he4f3b61755d7fa95
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x5624ba9bb607 - std::panicking::rust_panic_with_hook::hf00b8130f73095ec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x5624ba9bb444 - std::panicking::begin_panic::h6227f62cb2cdaeb4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x5624ba9bb3b9 - std::panicking::begin_panic_fmt::h173eadd80ae64bec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x5624ba996a80 - build_script_build::main::h99536cdaf4d8d14c
                        at /home/bburdette/.cargo/git/checkouts/portaudio-rs-00e07e26853f2e98/0b228f5/portaudio_sys/build.rs:8
   8:     0x5624ba9c3c4a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
   9:     0x5624ba9bbd46 - std::rt::lang_start::h65647f6e36cffdae
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  10:     0x5624ba996b32 - main
  11:     0x7f0dd59173f0 - __libc_start_main
  12:     0x5624ba995849 - _start
  13:                0x0 - <unknown>

bburdette@BB-5520:~/code/cyclofraust$ apt list --installed | grep portaudio

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libportaudio2/yakkety,now 19+svn20140130-1.1 amd64 [installed]
bburdette@BB-5520:~/code/cyclofraust$ 
```

**Comment by herrernst** [comment]
You also have to `apt-get install portaudio19-dev`

**Comment by bburdette** [comment]
argh, its been a while since I've used this.  working now.  the "portaudio19 is actually 2.0" thing was also confusing.  thanks!
